name: New word
description: Add a new vocabulary entry
title: "word: "
labels:
  - vocab
body:
  - type: input
    id: word
    attributes:
      label: Word
      placeholder: conflict
    validations:
      required: true

  - type: dropdown
    id: pos
    attributes:
      label: Part of speech
      options:
        - noun
        - verb
        - adjective
        - adverb
        - phrase
        - other
    validations:
      required: true

  - type: dropdown
    id: british
    attributes:
      label: British English?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: input
    id: spelling_us
    attributes:
      label: US spelling (if different)
      placeholder: color

  - type: input
    id: spelling_uk
    attributes:
      label: UK spelling (if different)
      placeholder: colour

  - type: input
    id: pronunciation
    attributes:
      label: Pronunciation (IPA etc.)
      placeholder: /ˈkɒnflɪkt/

  - type: input
    id: meaning_ja
    attributes:
      label: Meaning (Japanese)
      placeholder: 衝突、対立
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples (one per line)
      placeholder: |
        His statements on the subject conflicted.

  - type: input
    id: synonyms
    attributes:
      label: Synonyms (comma-separated)
      placeholder: struggle, clash

  - type: input
    id: tags
    attributes:
      label: Tags (comma-separated)
      placeholder: news, academic

  - type: input
    id: image_url
    attributes:
      label: Image URL (optional)
      placeholder: https://.../image.png

  - type: textarea
    id: notes
    attributes:
      label: Notes
