name: New word
description: Add a new vocabulary entry
title: "word: "
labels:
  - vocab
body:
  - type: input
    id: word
    attributes:
      label: Word
      placeholder: color
    validations:
      required: true

  - type: dropdown
    id: pos
    attributes:
      label: Part of speech
      options:
        - noun
        - verb
        - adjective
        - adverb
        - phrase
        - other
    validations:
      required: true

  - type: input
    id: other_spelling
    attributes:
      label: Other spelling (UK/US if different)
      placeholder: colour

  - type: input
    id: pronunciation
    attributes:
      label: Pronunciation (IPA etc.)
      placeholder: /ˈkʌlər/

  - type: input
    id: meaning_ja
    attributes:
      label: Meaning (Japanese)
      placeholder: 色
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples (one per line)

  - type: input
    id: synonyms
    attributes:
      label: Synonyms (comma-separated)

  - type: input
    id: tags
    attributes:
      label: Tags (comma-separated)

  - type: textarea
    id: notes
    attributes:
      label: Notes
