name: Update word
description: Update an existing vocabulary entry (only filled fields will be updated)
title: "update: "
labels:
  - vocab
body:
  - type: markdown
    attributes:
      value: |
        既存の単語を更新します。
        ✅ 空欄は「変更しない」扱いになります。
        ✅ Part of speech は (no change) のままなら変更されません。

  - type: input
    id: word
    attributes:
      label: Word (must match existing)
      placeholder: conflict
    validations:
      required: true

  - type: dropdown
    id: pos
    attributes:
      label: Part of speech (choose only if you want to change)
      options:
        - "(no change)"
        - noun
        - verb
        - adjective
        - adverb
        - phrase
        - other

  - type: input
    id: other_spelling
    attributes:
      label: Other spelling (UK/US if different)
      placeholder: colour

  - type: input
    id: pronunciation
    attributes:
      label: Pronunciation (IPA etc.)
      placeholder: /ˈkɒnflɪkt/

  - type: input
    id: meaning_ja
    attributes:
      label: Meaning (Japanese)
      placeholder: 衝突、対立

  - type: textarea
    id: examples
    attributes:
      label: Examples (one per line)
      placeholder: |
        His statements on the subject conflicted.

  - type: input
    id: synonyms
    attributes:
      label: Synonyms (comma-separated)
      placeholder: clash, dispute

  - type: input
    id: tags
    attributes:
      label: Tags (comma-separated)
      placeholder: news, academic

  - type: textarea
    id: notes
    attributes:
      label: Notes
