name: New word
description: Add a word
title: "word: "
labels:
  - vocab
body:
  - type: input
    id: word
    attributes:
      label: Word
      placeholder: generate
    validations:
      required: true
